### ISSUE TITLE
Fix it

### ISSUE THREAD

**Issue by RanolP** [OrigamiDream/Leveled-Storage#1]
* target/classes는 업로드할 필요 없음
* .idea와 .iml파일도 마찬가지
* ~~Maven 극혀...~~
* Storage#getObjects에서 방어를 위한 복사를 하세요.
* Storage#toString에 사용된 forEach를 고전적 for로 변경하면 성능 이득이 있을 수 있습니다.
* LeveledStorageObject#getElements와 LeveledStorageObject#getLayers는 하위 클래스가 protected 필드인 layers와 elements에 직접 접근할 수 있으므로 지워도 좋다고 생각합니다.
* 일부 상속 대상이 아닌 클래스에 final을 다세요.
* 일부 상속 대상이 아닌 함수에 final을 다세요.

이 프로젝트는 양호합니다.

**Comment by OrigamiDream** [comment]
target/classes <- 자동 업데이트
.idea .iml <- 자동 업데이트
MAVEN은 사랑입니다.
Storage#getObjects() 접수
Stroage#toString() 아 됐고 난 forEach를 사랑합니다.
getElements(), getLayers()는 API 용도입니다. 외부클래스에서의 참조를 허락합니다.

**Comment by RanolP** [comment]
getElements(), getLayers()가 protected인데 외부 클래스 참조 허락...?

**Comment by OrigamiDream** [comment]
인텔리제이 자동완성 ㅂㄷㅂㄷ

라놀램지님 다른건 없나여
